services:
  backend_dev:
    container_name: royal_api_dev
    image: backend_dev:1.0.0
    build:
      context: ../
      target: dev
      dockerfile: ./docker/Dockerfile
    env_file: .env
    command: npm run start:debug
    ports:
      - 5000:5000
      - 9229:9229
    network_mode: "host"
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    stdin_open: true
    restart: unless-stopped

  backend_prod:
    container_name: royal_api_prod
    image: backend_prod:1.0.0
    build:
      context: ../
      target: prod
      dockerfile: ./docker/Dockerfile
    env_file: .env
    command: npm run start:prod
    ports:
      - 5000:5000
      - 9229:9229
    network_mode: "host"
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    stdin_open: true
    restart: unless-stopped