version: '3.7'

services:
  uplix_postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    volumes:
      - uplix-postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432

  uplix_backend_dev:
    container_name: uplix_api_dev
    image: uplix_backend_dev
    build:
      context: ../
      target: dev
      dockerfile: ./docker/Dockerfile
    env_file: .env
    command: npm run start:debug
    ports:
      - 5000:5000
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - uplix_postgres
    stdin_open: true
    restart: unless-stopped

  uplix_backend_prod:
    container_name: uplix_api_prod
    image: uplix_backend_prod
    build:
      context: ../
      target: prod
      dockerfile: ./docker/Dockerfile
    env_file: .env
    command: npm run start:prod
    ports:
      - 5000:5000
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - uplix_postgres
    stdin_open: true
    restart: unless-stopped

volumes:
  uplix-postgres:
